# GRU953-Studio is free for non-commercial use under the PolyForm
# Noncommercial License 1.0.0. If it's useful to you, you can support its
# continued development — or enquire about a paid commercial licence — via
# the page linked below. No third-party donation account is required.
custom: ["https://github.com/GRU-953/GRU953-Studio/wiki/Sponsorship"]
