# GRU953-Studio is free for everyone, including commercial use, under the
# Apache License 2.0. If it's useful to you, you can support its continued
# development via the page linked below. Entirely optional — nothing about
# the licence depends on it. No third-party donation account is required.
custom: ["https://github.com/GRU-953/GRU953-Studio/wiki/Sponsorship"]
